<?php
return [
	'communication_api_username' => 'MedisageCommAPI',
	'communication_api_password' => 'CommAPI@Medi2021',
	'image_ext' => ["gif", "png", "jpeg", "jpg", "dng", "arw", "raw", "tif", "jfif", "svg", "pdf"],
	'askexpert_image_path' => 'askexperts/',
	'askexpert_storage_path' => "/public/askexpert/",
	'askexpert_public_storage_path' => "/app/public/askexpert/",
	'cases_path' => env('COULDFRONT_BASE_URL', '') . '/cases/',
	'videos_path' => env('COULDFRONT_BASE_URL', '') . '/video/',
	'slider_path' => env('COULDFRONT_BASE_URL', '') . '/slider/',
	'document_path' => env('COULDFRONT_BASE_URL', '') . '/documents/',
	'cme_path' => env('COULDFRONT_BASE_URL', '') . '/cme/',
	'notification_path' => env('COULDFRONT_BASE_URL', '') . '/notification/',
	'newsletter_path' => env('COULDFRONT_BASE_URL', '') . '/newsletter/',
	'immediate_action_path' => env('COULDFRONT_BASE_URL', '') . '/immediate_action/',
	'android_slider_path' => env('COULDFRONT_BASE_URL', '') . '/slider/android/',
	'ios_slider_path' => env('COULDFRONT_BASE_URL', '') . '/slider/ios/',
	'article_path' => env('COULDFRONT_BASE_URL', '') . '/article/',
	'series_path' => env('COULDFRONT_BASE_URL', '') . '/series/',
	'certificates_path' => 'app/public/members/certificates/template/images/',
	'certificate_template_path' => 'members/certificates/template/images/',
	'live_event_path' => env('COULDFRONT_BASE_URL', '') . '/live_event_banner_image/',
	'live_event_thumbnail_path' => env('COULDFRONT_BASE_URL', '') . '/live_event_thumbnail_image/',
	'image_path' => env('COULDFRONT_BASE_URL', '') . '/image-bank/',
	'promotion_image_path' => env('COULDFRONT_BASE_URL', '') . '/promotion/',
	'log_file_path' => env('COULDFRONT_BASE_URL', '') . '/Logs/UniversalUpload/',
	'forum_types' => array(
		array("value" => "college", "name" => "College"),
		array("value" => "disease", "name" => "Disease"),
		array("value" => "partner", "name" => "Partner"),
		array("value" => "associate", "name" => "Associate"),
		array("value" => "hospital", "name" => "Hospital"),
		array("value" => "doctor", "name" => "Doctor")
	),
	"user_type_array" => array(
		array("name" => "Practicing Doctor", "value" => "doctor"),
		array("name" => "Ayush Doctor", "value" => "ayush_doctor"),
		array("name" => "PG Student", "value" => "pg_student"),
		array("name" => "UG Student", "value" => "ug_student"),
		//array("name" => "Other","value"=>"other"),
		array("name" => "Retired/Not Practicing Doctor", "value" => "retired_not_practicing_doctor"),
		array("name" => "Health care Administrator", "value" => "health_care_administrator"),
		array("name" => "Nurses", "value" => "nurses"),
		array("name" => "Pharmacist", "value" => "pharmacist"),
		array("name" => "Allied Health care worker", "value" => "allied_health_care_worker"),
		array("name" => "Technician", "value" => "technician"),
		array("name" => "Psychologists", "value" => "psychologists"),
		array("name" => "Any other", "value" => "any_other"),

	),
	'points' => [
		'journal' => 1,
		'newsletter' => 10,
		'video'	=> 10,
		'cases' => 25,
		'reply' => 2,
		'like' => 1,
	],
	"data_filter_member_types" => array(
		array("value" => 'All', "name" => "All"),
		array("value" => 'universal', "name" => "Universal"),
		array("value" => 'digiMR', "name" => "Digi MR"),
		array("value" => 'live_event', "name" => "Live event"),
		array("value" => 'member', "name" => "Member"),
		array("value" => 'app_user', "name" => "App User"),
		array("value" => 'prime_user', "name" => "Prime User")
	),
	"QUESTION_BANK_TYPES" => array(
		array("value" => 'mcq', "name" => "MCQ"),
		array("value" => 'input', "name" => "Input"),
		array("value" => 'star_rating', "name" => "Star Rating"),
	),
	"ATTACHMENT_TYPES" => array(
		array("value" => 'video', "name" => "Video"),
		array("value" => 'reading_material', "name" => "Reading Material"),
		array("value" => 'forum', "name" => "Forum"),
		array("value" => 'live_event', "name" => "Live Event"),
		array("value" => 'live_event_registration', "name" => "Live Event Registration")
	),
	'DIGIMR_SECONDARY_STATUS' => ['All','CALL_BACK_LATER', 'NO_RESPONSE', 'CALL_DONE_WITH_MORE_INFO_NEEDED', 'CALL_SUCCESSFUL', 'NOT_INTERESTED', 'INVALID_PHONE_NUMBER', 'NOT_REACHABLE', 'null'],
	'whatsapp_active_status' => ['All','not attempted', 'not sent', 'failed', 'delivered', 'read', 'clicked', 'replied', 'null'],
	'sms_active_status' => ['All','not sent', 'delivered', 'clicked', 'null'],
	'REGISTRATION_UNNECCESSORY_COLUMNS' => ['id', 'ip_address', 'deleted_at', 'created_at', 'updated_at', 'device_id', 'device_token'],

	'partner_image_path' => env('COULDFRONT_BASE_URL', '') . '/partner/',
	'expert_image_path' => env('COULDFRONT_BASE_URL', '') . '/expert/',
	'video_image_path' => env('COULDFRONT_BASE_URL', '') . '/video/',
	'page_image_path' =>  env('COULDFRONT_BASE_URL', '') . '/slider/',
	'podcast_image_path' => env('COULDFRONT_BASE_URL', '') . '/podcast/',
	'community_image_path' =>  env('COULDFRONT_BASE_URL', '') . '/mcat/',
    'mci_image_path' => env('COULDFRONT_BASE_URL', '') . '/mcidocs/',

	'QUESTIONS_USER_TYPE' => array("NORMAL" => 0, "ADMIN" => 1, "EXPERT" => 2),
	'COULDFRONT_BASE_URL' => env('COULDFRONT_BASE_URL', ''),


	'videocrypt_access_key' => env("VIDEOCRYPT_ACCESS_KEY"),
	'videocrypt_secret_key' => env("VIDEOCRYPT_SECRET_KEY"),
	'videocrypt_base_url' => env("VIDEOCRYPT_BASE_URL"),
	'DEFAULT_VIDEO_CRYPT' => 2,
	'WEBSITE_URL' => env("WEBSITE_URL", 'https://mymedisage.com'),
	'delete_notification_logs_days' => 3
];
