<?php
return [
    'council_data' => [
        array("state" => "Andhra Pradesh Medical Council"),
        array("state" => "Arunachal Pradesh Medical Council"),
        array("state" => "Assam Medical Council"),
        array("state" => "Bihar Medical Council"),
        array("state" => "Chattisgarh Medical Council"),
        array("state" => "Delhi Medical Council"),
        array("state" => "Goa Medical Council"),
        array("state" => "Gujarat Medical Council"),
        array("state" => "Haryana State Dental & Medical Council"),
        array("state" => "Himachal Pradesh Medical Council"),
        array("state" => "Jammu & Kashmir Medical Council"),
        array("state" => "Jharkhand Medical Council"),
        array("state" => "Karnataka Medical Council"),
        array("state" => "Kerala Medical Council"),
        array("state" => "Madhya Pradesh Medical Council"),
        array("state" => "Maharashtra Medical Council"),
        array("state" => "Manipur Medical Council"),
        array("state" => "Meghalya Medical Council"),
        array("state" => "Mizoram Medical Council"),
        array("state" => "National Medical Council"),
        array("state" => "Nagaland Medical Council"),
        array("state" => "Orissa Medical Council"),
        array("state" => "Punjab Medical Council"),
        array("state" => "Rajasthan Medical Council"),
        array("state" => "Sikkim Medical Council"),
        array("state" => "Tamil Nadu Medical Council"),
        array("state" => "Telangana Medical Council"),
        array("state" => "Tripura Medical Council"),
        array("state" => "Uttarnchal Medical Council"),
        array("state" => "Uttar Pradesh Medical Council"),
        array("state" => "West Bengal Medical Council"),
    ],

];
